# Generated by Django 2.2 on 2019-04-09 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('middleName', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Women')], default='M', max_length=1)),
                ('birth_date', models.DateTimeField(verbose_name='BirthDate')),
                ('phone_number', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('Res', models.IntegerField()),
                ('Patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='clinic.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='clinic.UserProfile', verbose_name='Доктор')),
                ('patient', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='clinic.UserProfile', verbose_name='Пациент')),
            ],
        ),
    ]
