# Generated by Django 2.2 on 2019-04-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Women')], default='M', max_length=1)),
                ('birth_date', models.DateTimeField(verbose_name='BirthDate')),
                ('phoneNumber', models.CharField(max_length=12)),
                ('results', models.ManyToManyField(to='clinic.Result')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('middleName', models.CharField(max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Women')], default='M', max_length=1)),
                ('birth_date', models.DateTimeField(verbose_name='BirthDate')),
                ('phoneNumber', models.CharField(max_length=12)),
                ('clients', models.ManyToManyField(to='clinic.Client')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
