# Generated by Django 2.2 on 2019-04-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='middleName',
            new_name='middle_name',
        ),
    ]
